version: '3.8'

#Comandos para adicionar o hash no banco de dados
#
#  docker exec -it (identificador do container) bash
#  mysql -u root -p vollmed_api
#  senha root: root_password
#  select * from usuarios;
#  insert into usuarios values (1, 'ana.souza@voll.med', '$2a$10$Y50UaMFOxteibQEYLrwuHeehHYfcoafCopUazP12.rqB41bsolF5.');

#services:
#  db:
#    image: mysql:8.0.31
#    volumes:
#      - dbbase:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: bp1234
#      MYSQL_DATABASE: vollmed_api

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql_container
    volumes:
      - dbbase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: rafael
      MYSQL_PASSWORD: leafar
    ports:
      - "3306:3306"
#    networks:
#      - cadastrousuario_default


volumes:
  dbbase:

#networks:
#  cadastrousuario_default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
